In [7]:
import pandas as pd 

data_mentah = pd.read_json("detection_output.jsonl", lines=True)
data_mentah

,classes,person_encodings
0,"[mesin, Tidak rompi keselamatan]","[[-0.058796722441911003, 0.11140788346529001, ..."
1,"[Tidak masker, Tidak helm pengaman, Tidak romp...","[[-0.033897340297698, 0.08929627388715701, 0.0..."
2,"[Tidak masker, Tidak rompi keselamatan, Tidak ...","[[-0.032618880271911004, 0.1005120575428, 0.10..."
3,"[Tidak masker, Tidak helm pengaman, Tidak romp...","[[-0.050972614437341, 0.099794402718544, 0.103..."
4,"[Tidak masker, Tidak helm pengaman, Tidak romp...","[[-0.036173824220895004, 0.099524721503257, 0...."
...,...,...
86,"[Tidak masker, Tidak masker, Tidak helm pengam...","[[-0.038731999695301, 0.10349906235933301, 0.0..."
87,"[Tidak masker, Tidak masker, Tidak helm pengam...","[[-0.04709155857563, 0.09712466597557001, 0.05..."
88,"[Tidak masker, Tidak masker, Tidak helm pengam...","[[-0.037510670721530005, 0.099210053682327, 0...."
89,"[Tidak masker, Tidak masker, Tidak rompi kesel...","[[-0.017817262560129003, 0.07305812835693301, ..."
90,"[Tidak masker, Tidak masker, Tidak rompi kesel...","[[-0.027508458122611, 0.09550033509731201, 0.0..."

In [8]:
import json

clean = []
with open("face_encodings.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        fixed = line.replace("'", '"').strip()
        clean.append(fixed)

with open("face_encoding_fixed.jsonl", "w", encoding="utf-8") as f:
    f.write("\n".join(clean))


data_asli = pd.read_json("face_encoding_fixed.jsonl", lines=True)
data_asli

    nama                                           encoding
0  agung  [-0.09862457960844001, 0.11294294893741601, 0....