In [1]:
import pandas as pd
import numpy as np

data = np.array([1,2,3,4,5])
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
df = pd.DataFrame(data)
df

   0
0  1
1  2
2  3
3  4
4  5

In [10]:
# assignment

data = np.array(["apple", "orange", "banana", "grape", "mango"])
series = pd.Series(data)
df = pd.DataFrame(data)
series

0     apple
1    orange
2    banana
3     grape
4     mango
dtype: object

In [11]:
df

        0
0   apple
1  orange
2  banana
3   grape
4   mango