In [29]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Membuat dataframe contoh
data = {
    'I': [100, 90, 20, 95],
    'II': [30, 45, 56, 10],
    'III': [20, 40, 80, 98]
}

df = pd.DataFrame(data)

# Inisialisasi StandardScaler
scaler = StandardScaler()

# Fit StandardScaler pada kolom 'I'
scaler.fit(df[['I']]) # menggunakan [[]] bukan [] karena standard scaler menggunakan data 2D / dataframe

# Tampilkan rata-rata dan deviasi standar yang telah dihitung
print("Rata-rata:", scaler.mean_)
print("Deviasi Standar:", scaler.scale_)

Rata-rata: [76.25]
Deviasi Standar: [32.66783586]

Setelah mendapatkan rata-rata dan standar deviasi dari scaler.fit, selanjutnya menggunakan transform untuk mencari nilai skala standar setiap data nya sebagai berikut :

data kolom I pertama = 100

skala standar = ( data - mean ) / standar deviasi

data pertama = ( 100 - 76.25 ) / 32.66783586 = 0.7270148

proses perhitungan dilakukan sampai data terakhir.

In [25]:
# Transformasi data pada kolom 'I' menjadi skala standar
scaled_data = scaler.transform(df[['I']])

# Tampilkan dataframe hasil
print(scaled_data)

[[ 0.7270148 ]
 [ 0.4209033 ]
 [-1.72187715]
 [ 0.57395905]]

Dalam konteks skala standar:

Jika hasil transformasi positif, itu berarti nilai tersebut berada diatas mean.

Jika hasil transformasi negatif, itu berarti nilai tersebut berada di bawah mean.

Jika hasil transformasi adalah 0, itu berarti nilai tersebut sama dengan mean.

In [27]:
# ubah hasil transform kedalam kolom dataframe

scaled_df = pd.DataFrame(scaled_data, columns=['scaled'])

scaled_df

     scaled
0  0.727015
1  0.420903
2 -1.721877
3  0.573959

In [30]:
scaler.fit(df[['I']].values)

StandardScaler()

In [35]:
tanpa_reshape = df[['I']].values
reshape = df[['I']].values.reshape(2,2)

print(tanpa_reshape)
print(reshape)

[[100]
 [ 90]
 [ 20]
 [ 95]]
[[100  90]
 [ 20  95]]

In [36]:
from google.colab import files

uploaded = files.upload()

Saving employee (1).csv to employee (1).csv

In [37]:
data = pd.read_csv('employee (1).csv')

data.head()

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

In [41]:
scaler.fit(data[['performance_score']])

print('rata-rata = ',scaler.mean_)
print('standar deviasi = ',scaler.scale_)

rata-rata =  [610.66666667]
standar deviasi =  [222.19360927]

In [43]:
data['performance_std_scaler'] = scaler.transform(data[['performance_score']])

In [44]:
data

,name,age,income,gender,department,grade,performance_score,performance_std_scaler
0,Allen Smith,45.0,NaN,NaN,Operations,G3,723,0.505565
1,S Kumar,NaN,16000.0,F,Finance,G0,520,-0.408053
2,Jack Morgan,32.0,35000.0,M,Finance,G2,674,0.285037
3,Ying Chin,45.0,65000.0,F,Sales,G3,556,-0.246032
4,Dheeraj Patel,30.0,42000.0,F,Operations,G2,711,0.451558
5,Satyam Sharma,NaN,62000.0,NaN,Sales,G3,649,0.172522
6,James Authur,54.0,NaN,F,Operations,G3,53,-2.509823
7,Josh Wills,54.0,52000.0,F,Finance,G3,901,1.306668
8,Leo Duck,23.0,98000.0,M,Sales,G4,709,0.442557

In [59]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Contoh data harga saham dua perusahaan (harga penutupan harian dalam dolar)
data = {
    'Saham_A': [100, 10,50,39],
    'Saham_B': [50, 70,55,33]
}

df = pd.DataFrame(data)

# Inisialisasi StandardScaler
scaler = StandardScaler()

# Fit StandardScaler pada dataframe
scaler.fit(df)

# Transformasi data dalam skala standar
scaled_data = scaler.transform(df)

# Hasilnya adalah dataframe baru dengan data dalam skala standar
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

# Tampilkan dataframe hasil
print(scaled_df)

    Saham_A   Saham_B
0  1.546932 -0.151402
1 -1.223693  1.362620
2  0.007696  0.227103
3 -0.330936 -1.438321

In [56]:
data['Saham_A'].values.plot(kind = 'line')
data['Saham_B'].values.plot(kind = 'line')

AttributeError: ignored

In [58]:
data['Saham_A']

[100, 10, 50, 39]