In [24]:
import pandas as pd 

df = pd.read_csv("car_data.csv")
df

     User ID  Gender  Age  AnnualSalary  Purchased
0        385    Male   35         20000          0
1        681    Male   40         43500          0
2        353    Male   49         74000          0
3        895    Male   40        107500          1
4        661    Male   25         79000          0
..       ...     ...  ...           ...        ...
995      863    Male   38         59000          0
996      800  Female   47         23500          0
997      407  Female   28        138500          1
998      299  Female   48        134000          1
999      687  Female   44         73500          0

[1000 rows x 5 columns]

In [25]:
df.isnull().sum()

User ID         0
Gender          0
Age             0
AnnualSalary    0
Purchased       0
dtype: int64

In [26]:
df.describe()

           User ID          Age   AnnualSalary    Purchased
count  1000.000000  1000.000000    1000.000000  1000.000000
mean    500.500000    40.106000   72689.000000     0.402000
std     288.819436    10.707073   34488.341867     0.490547
min       1.000000    18.000000   15000.000000     0.000000
25%     250.750000    32.000000   46375.000000     0.000000
50%     500.500000    40.000000   72000.000000     0.000000
75%     750.250000    48.000000   90000.000000     1.000000
max    1000.000000    63.000000  152500.000000     1.000000

In [27]:
x = df[["Gender", "Age", "AnnualSalary"]]
y = df[["Purchased"]]

In [28]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

encoder = LabelEncoder()
scaler = MinMaxScaler()

x["Gender"] = encoder.fit_transform(x["Gender"])
x[["Age", "AnnualSalary"]] = scaler.fit_transform(x[["Age", "AnnualSalary"]])

/var/folders/q2/2h4p204s56d3vhv_jx5hmc6m0000gn/T/ipykernel_1747/1321321570.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["Gender"] = encoder.fit_transform(x["Gender"])
/var/folders/q2/2h4p204s56d3vhv_jx5hmc6m0000gn/T/ipykernel_1747/1321321570.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[["Age", "AnnualSalary"]] = scaler.fit_transform(x[["Age", "AnnualSalary"]])

In [29]:
from sklearn.model_selection import train_test_split 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [30]:
from sklearn.tree import DecisionTreeClassifier 

model = DecisionTreeClassifier(random_state=42, ccp_alpha=0.01) 
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

model.score(x_test, y_test)

0.905

In [44]:
df_baru = pd.DataFrame({
    "Actual" : y_test["Purchased"].values,
    "Predict" : y_pred
})

df_baru

     Actual  Predict
0         0        0
1         1        1
2         0        0
3         1        1
4         0        1
..      ...      ...
195       0        0
196       0        0
197       1        1
198       0        0
199       1        1

[200 rows x 2 columns]