In [51]:
import pandas as pd

df = pd.read_csv("death.csv")
df

,Cause,Type,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL
0,Abrasi Air Laut,Bencana Alam,2012,1,0,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...
1,AIDS,Bencana Non Alam dan Penyakit,2000,1,47,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
2,AIDS,Bencana Non Alam dan Penyakit,2001,1,99,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
3,AIDS,Bencana Non Alam dan Penyakit,2002,1,100,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
4,AIDS,Bencana Non Alam dan Penyakit,2003,1,261,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...
...,...,...,...,...,...,...,...,...
675,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2016,1,0,Profil Kesehatan Indonesia Tahun 2016,Lampiran 6.37,https://pusdatin.kemkes.go.id/download.php?fil...
676,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2017,1,0,Profil Kesehatan Indonesia Tahun 2017,Lampiran 6.43,https://pusdatin.kemkes.go.id/download.php?fil...
677,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2019,1,0,Profil Kesehatan Indonesia Tahun 2019,Lampiran 63.c,https://pusdatin.kemkes.go.id/download.php?fil...
678,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2020,1,0,Profil Kesehatan Indonesia Tahun 2020,191,https://pusdatin.kemkes.go.id/download.php?fil...
679,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2021,1,0,Profil Kesehatan Indonesia Tahun 2021,253,https://www.kemkes.go.id/downloads/resources/d...

In [52]:
df.isnull().sum()

Cause              0
Type               0
Year               0
Data Redundancy    0
Total Deaths       0
Source             0
Page at Source     2
Source URL         3
dtype: int64

In [53]:
df.dropna(inplace=True)
df

,Cause,Type,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL
0,Abrasi Air Laut,Bencana Alam,2012,1,0,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...
1,AIDS,Bencana Non Alam dan Penyakit,2000,1,47,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
2,AIDS,Bencana Non Alam dan Penyakit,2001,1,99,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
3,AIDS,Bencana Non Alam dan Penyakit,2002,1,100,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
4,AIDS,Bencana Non Alam dan Penyakit,2003,1,261,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...
...,...,...,...,...,...,...,...,...
675,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2016,1,0,Profil Kesehatan Indonesia Tahun 2016,Lampiran 6.37,https://pusdatin.kemkes.go.id/download.php?fil...
676,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2017,1,0,Profil Kesehatan Indonesia Tahun 2017,Lampiran 6.43,https://pusdatin.kemkes.go.id/download.php?fil...
677,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2019,1,0,Profil Kesehatan Indonesia Tahun 2019,Lampiran 63.c,https://pusdatin.kemkes.go.id/download.php?fil...
678,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2020,1,0,Profil Kesehatan Indonesia Tahun 2020,191,https://pusdatin.kemkes.go.id/download.php?fil...
679,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2021,1,0,Profil Kesehatan Indonesia Tahun 2021,253,https://www.kemkes.go.id/downloads/resources/d...

In [54]:
df.drop_duplicates(inplace=True)

In [55]:
q1 = df["Total Deaths"].quantile(0.25)
q3 = df["Total Deaths"].quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

df_clean = df[ (df["Total Deaths"] >= lower_bound) & (df["Total Deaths"] <= upper_bound) ]
df_clean.to_csv("death_clean.csv", index = False)

Encoding

encoding adalah proses mengubah data kategori menjadi format numerik. 

beberapa metode encoding : 

1. one hot encoding : metode yang mengubah setiap kategori menjadi true (1) dan false (0).
2. label encoding : metode yang memberikan setiap kategori nilai integer yang unik (0,1,2,3,4).

Perbedaan one hot dengan label encoding : 
1. one hot digunakan jika datanya tidak terurut.
2. label encoding digunakan jika datanya terurut.

In [56]:
# one hot encoding 

df_hot = pd.get_dummies(df_clean, columns=["Cause", "Type"])
df_hot

,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL,Cause_AIDS,Cause_Abrasi Air Laut,Cause_Aksi Teror dan Sabotase,Cause_Angin Puting Beliung,...,Cause_Rubella,Cause_Tanah Longsor,Cause_Tersambar Petir,Cause_Tetanus,Cause_Tetanus Neonatorium,Cause_Tsunami,Cause_Wabah Penyakit (Epidemi),Type_Bencana Alam,Type_Bencana Non Alam dan Penyakit,Type_Bencana Sosial
0,2012,1,0,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
1,2000,1,47,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,2001,1,99,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,2002,1,100,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,2003,1,261,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675,2016,1,0,Profil Kesehatan Indonesia Tahun 2016,Lampiran 6.37,https://pusdatin.kemkes.go.id/download.php?fil...,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
676,2017,1,0,Profil Kesehatan Indonesia Tahun 2017,Lampiran 6.43,https://pusdatin.kemkes.go.id/download.php?fil...,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
677,2019,1,0,Profil Kesehatan Indonesia Tahun 2019,Lampiran 63.c,https://pusdatin.kemkes.go.id/download.php?fil...,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
678,2020,1,0,Profil Kesehatan Indonesia Tahun 2020,191,https://pusdatin.kemkes.go.id/download.php?fil...,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
679,2021,1,0,Profil Kesehatan Indonesia Tahun 2021,253,https://www.kemkes.go.id/downloads/resources/d...,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False

In [57]:
# label encoding 

from sklearn.preprocessing import LabelEncoder

encode = LabelEncoder()
df_label = df_clean.copy()
df_label["Type"] = encode.fit_transform(df_label["Type"])
df_label

,Cause,Type,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL
0,Abrasi Air Laut,0,2012,1,0,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...
1,AIDS,1,2000,1,47,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
2,AIDS,1,2001,1,99,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
3,AIDS,1,2002,1,100,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
4,AIDS,1,2003,1,261,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...
...,...,...,...,...,...,...,...,...
675,Wabah Penyakit (Epidemi),1,2016,1,0,Profil Kesehatan Indonesia Tahun 2016,Lampiran 6.37,https://pusdatin.kemkes.go.id/download.php?fil...
676,Wabah Penyakit (Epidemi),1,2017,1,0,Profil Kesehatan Indonesia Tahun 2017,Lampiran 6.43,https://pusdatin.kemkes.go.id/download.php?fil...
677,Wabah Penyakit (Epidemi),1,2019,1,0,Profil Kesehatan Indonesia Tahun 2019,Lampiran 63.c,https://pusdatin.kemkes.go.id/download.php?fil...
678,Wabah Penyakit (Epidemi),1,2020,1,0,Profil Kesehatan Indonesia Tahun 2020,191,https://pusdatin.kemkes.go.id/download.php?fil...
679,Wabah Penyakit (Epidemi),1,2021,1,0,Profil Kesehatan Indonesia Tahun 2021,253,https://www.kemkes.go.id/downloads/resources/d...

Data transform (transformasi data)

Data transform adalah proses mengubah data numerik ke dalam skala yang berbeda.

Tipe data transform : 

1. Normalisasi : proses merubah skala data ke rentang 0 sampai 1

In [58]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_normal = df_clean.copy()
df_normal[["Total Deaths"]] = scaler.fit_transform(df_normal[["Total Deaths"]])
df_normal

,Cause,Type,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL
0,Abrasi Air Laut,Bencana Alam,2012,1,0.000000,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...
1,AIDS,Bencana Non Alam dan Penyakit,2000,1,0.066104,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
2,AIDS,Bencana Non Alam dan Penyakit,2001,1,0.139241,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
3,AIDS,Bencana Non Alam dan Penyakit,2002,1,0.140647,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
4,AIDS,Bencana Non Alam dan Penyakit,2003,1,0.367089,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...
...,...,...,...,...,...,...,...,...
675,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2016,1,0.000000,Profil Kesehatan Indonesia Tahun 2016,Lampiran 6.37,https://pusdatin.kemkes.go.id/download.php?fil...
676,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2017,1,0.000000,Profil Kesehatan Indonesia Tahun 2017,Lampiran 6.43,https://pusdatin.kemkes.go.id/download.php?fil...
677,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2019,1,0.000000,Profil Kesehatan Indonesia Tahun 2019,Lampiran 63.c,https://pusdatin.kemkes.go.id/download.php?fil...
678,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2020,1,0.000000,Profil Kesehatan Indonesia Tahun 2020,191,https://pusdatin.kemkes.go.id/download.php?fil...
679,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2021,1,0.000000,Profil Kesehatan Indonesia Tahun 2021,253,https://www.kemkes.go.id/downloads/resources/d...

Data splitting 

Data splitting adalah proses membagi dataset menjadi data training dan data testing.

Sebelum melakukan data splitting, harus memilih data fitur dan data target.

In [59]:
x = df_clean[["Cause", "Type"]] # data fitur
y = df_clean[["Total Deaths"]] # data target

In [60]:
from sklearn.model_selection import train_test_split

x_encode = pd.get_dummies(x) # one hot encoding

scaler_y = MinMaxScaler()
y_norm = scaler_y.fit_transform(y).ravel() # normalisasi

# ravel mengubah data 2 dimensi menjadi 1 dimensi

x_train, x_test, y_train, y_test = train_test_split(x_encode, y_norm, test_size=0.2)

# test size = 0.2, data training 80% data testing 20%

print(f"x_train = {len(x_train)}, x_test = {len(x_test)}")
print(f"y_train = {len(y_train)}, y_test = {len(y_test)}")

x_train = 440, x_test = 110
y_train = 440, y_test = 110

ASSIGNMENT

In [61]:
mall = pd.read_csv("Mall_Customers.csv")
mall_clean = mall.copy()

In [62]:
mall_clean.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [63]:
q1 = mall_clean["Spending Score (1-100)"].quantile(0.25)
q3 = mall_clean["Spending Score (1-100)"].quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

clean = mall_clean[(mall_clean["Spending Score (1-100)"] >= lower_bound) & (mall_clean["Spending Score (1-100)"] <= upper_bound)]
clean

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [64]:
z = mall_clean[["Gender", "Age", "Annual Income (k$)"]] 
b = mall_clean[["Spending Score (1-100)"]] 

z = pd.get_dummies(z, columns=["Gender"], drop_first = True)

scale_age = MinMaxScaler()
z[["Age"]] = scale_age.fit_transform(z[["Age"]]) #ini namanya normalisasi

scale_annual = MinMaxScaler()
z[["Annual Income (k$)"]] = scale_age.fit_transform(z[["Annual Income (k$)"]])

KeyError: "None of [Index(['AAnnual Income (k$)'], dtype='object')] are in the [columns]"

In [66]:
z = mall_clean[["Gender", "Age", "Annual Income (k$)"]] 
b = mall_clean[["Spending Score (1-100)"]] 

z = pd.get_dummies(z, columns=["Gender"], drop_first=True)

scale_age = MinMaxScaler()
z[["Age"]] = scale_age.fit_transform(z[["Age"]])

scale_annual = MinMaxScaler()
z[["Annual Income (k$)"]] = scale_age.fit_transform(z[["Annual Income (k$)"]])

scale_spending = MinMaxScaler()
b = scale_spending.fit_transform(b).ravel()

array([0.3877551 , 0.81632653, 0.05102041, 0.7755102 , 0.39795918,
       0.76530612, 0.05102041, 0.94897959, 0.02040816, 0.7244898 ,
       0.13265306, 1.        , 0.14285714, 0.7755102 , 0.12244898,
       0.79591837, 0.34693878, 0.66326531, 0.28571429, 0.98979592,
       0.34693878, 0.73469388, 0.04081633, 0.73469388, 0.13265306,
       0.82653061, 0.31632653, 0.6122449 , 0.30612245, 0.87755102,
       0.03061224, 0.73469388, 0.03061224, 0.92857143, 0.13265306,
       0.81632653, 0.16326531, 0.73469388, 0.25510204, 0.75510204,
       0.34693878, 0.92857143, 0.35714286, 0.6122449 , 0.2755102 ,
       0.65306122, 0.55102041, 0.46938776, 0.41836735, 0.41836735,
       0.52040816, 0.60204082, 0.54081633, 0.60204082, 0.44897959,
       0.40816327, 0.5       , 0.45918367, 0.51020408, 0.45918367,
       0.56122449, 0.55102041, 0.52040816, 0.59183673, 0.51020408,
       0.59183673, 0.5       , 0.47959184, 0.59183673, 0.46938776,
       0.55102041, 0.41836735, 0.48979592, 0.56122449, 0.46938776,
       0.54081633, 0.53061224, 0.47959184, 0.52040816, 0.41836735,
       0.51020408, 0.55102041, 0.40816327, 0.43877551, 0.57142857,
       0.45918367, 0.58163265, 0.55102041, 0.60204082, 0.45918367,
       0.55102041, 0.40816327, 0.48979592, 0.39795918, 0.41836735,
       0.52040816, 0.46938776, 0.5       , 0.41836735, 0.48979592,
       0.40816327, 0.47959184, 0.59183673, 0.55102041, 0.56122449,
       0.41836735, 0.5       , 0.45918367, 0.42857143, 0.47959184,
       0.52040816, 0.54081633, 0.41836735, 0.45918367, 0.47959184,
       0.5       , 0.42857143, 0.59183673, 0.42857143, 0.57142857,
       0.56122449, 0.39795918, 0.58163265, 0.91836735, 0.28571429,
       0.7755102 , 0.34693878, 0.95918367, 0.10204082, 0.75510204,
       0.08163265, 0.75510204, 0.33673469, 0.71428571, 0.04081633,
       0.8877551 , 0.06122449, 0.73469388, 0.09183673, 0.7244898 ,
       0.04081633, 0.93877551, 0.39795918, 0.87755102, 0.1122449 ,
       0.97959184, 0.35714286, 0.74489796, 0.21428571, 0.90816327,
       0.16326531, 0.8877551 , 0.19387755, 0.76530612, 0.15306122,
       0.89795918, 0.        , 0.78571429, 0.        , 0.73469388,
       0.34693878, 0.83673469, 0.04081633, 0.93877551, 0.25510204,
       0.75510204, 0.19387755, 0.95918367, 0.26530612, 0.63265306,
       0.12244898, 0.75510204, 0.09183673, 0.92857143, 0.12244898,
       0.86734694, 0.14285714, 0.69387755, 0.13265306, 0.90816327,
       0.31632653, 0.86734694, 0.14285714, 0.8877551 , 0.3877551 ,
       0.97959184, 0.23469388, 0.68367347, 0.16326531, 0.85714286,
       0.2244898 , 0.69387755, 0.07142857, 0.91836735, 0.15306122,
       0.79591837, 0.2755102 , 0.74489796, 0.17346939, 0.83673469])