Random forest 

- random forest regressor 
    digunakan ketika outputnya adalah nilai kontinu

- random forest classifier
    digunakan ketika outputnya berupa kategori

kelebihan random forest : 
    1. akurasi lebih bagus 
    2. mengurangi resiko overfitting 
    3. Robust terhadap data hilang atau outlier

Random forest regressor

In [47]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler 
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv("death_clean.csv")

df.head()

,Cause,Type,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL
0,Abrasi Air Laut,Bencana Alam,2012,1,0,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...
1,AIDS,Bencana Non Alam dan Penyakit,2000,1,47,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
2,AIDS,Bencana Non Alam dan Penyakit,2001,1,99,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
3,AIDS,Bencana Non Alam dan Penyakit,2002,1,100,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
4,AIDS,Bencana Non Alam dan Penyakit,2003,1,261,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...

In [48]:
x = df[["Cause", "Type"]]
y = df[["Total Deaths"]]

x = pd.get_dummies(x, columns=["Cause", "Type"])

scaler = MinMaxScaler()
y = scaler.fit_transform(y).ravel()

In [49]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [50]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([1.25279078e-01, 7.52600964e-02, 3.00020092e-02, 6.08771354e-02,
       1.13331298e-01, 1.13331298e-01, 7.52600964e-02, 6.27106914e-04,
       7.70852518e-03, 2.21940928e-02, 8.43881857e-05, 6.07668127e-01,
       7.52600964e-02, 1.48973277e-01, 3.87408345e-01, 7.52600964e-02,
       6.27106914e-04, 6.07668127e-01, 9.28914674e-03, 2.72411314e-02,
       2.84106892e-02, 1.82869198e-01, 1.95937312e-01, 1.24034808e-02,
       7.52600964e-02, 9.06391624e-05, 8.43881857e-05, 2.88788204e-02,
       1.03427489e-01, 1.03427489e-01, 1.13130149e-02, 2.10970464e-04,
       6.27106914e-04, 7.52600964e-02, 3.35240991e-02, 7.52600964e-02,
       6.07668127e-01, 1.82869198e-01, 8.47452448e-02, 8.47452448e-02,
       1.25279078e-01, 7.03234880e-05, 1.06891702e-02, 7.52600964e-02,
       3.35240991e-02, 2.36821378e-01, 1.13331298e-01, 1.03427489e-01,
       2.41544803e-02, 1.03427489e-01, 2.84106892e-02, 2.11661463e-02,
       7.03234880e-05, 6.27106914e-04, 1.23850324e-02, 2.33065908e-03,
       1.13331298e-01, 1.13331298e-01, 1.18904333e-01, 5.99629630e-01,
       6.27106914e-04, 6.27106914e-04, 1.79512591e-02, 1.92463331e-01,
       6.08771354e-02, 6.07668127e-01, 1.82401514e-01, 2.36821378e-01,
       1.13331298e-01, 1.18904333e-01, 7.52600964e-02, 6.27106914e-04,
       1.23850324e-02, 7.62306610e-03, 7.52600964e-02, 6.27106914e-04,
       3.35240991e-02, 3.35240991e-02, 1.13331298e-01, 1.61412721e-01,
       7.52600964e-02, 1.23850324e-02, 3.42919289e-02, 2.11661463e-02,
       9.06391624e-05, 2.11661463e-02, 3.42919289e-02, 1.78878149e-01,
       3.51165026e-02, 1.03427489e-01, 1.83802991e-01, 2.10970464e-04,
       2.44145291e-02, 2.41544803e-02, 2.10970464e-04, 6.07668127e-01,
       6.27106914e-04, 1.96200111e-02, 6.27106914e-04, 2.10970464e-04,
       7.70852518e-03, 1.18904333e-01, 1.06782415e-01, 6.27106914e-04,
       7.03234880e-05, 1.83802991e-01, 7.91440404e-01, 6.27106914e-04,
       7.79726743e-03, 1.23850324e-02, 4.44634653e-02, 3.35240991e-02,
       7.79726743e-03, 1.06782415e-01, 2.33065908e-03, 2.33065908e-03,
       1.13331298e-01, 2.33065908e-03, 1.18904333e-01, 3.00020092e-02,
       2.21940928e-02, 1.78878149e-01, 3.88908981e-02, 1.13130149e-02,
       9.06391624e-05, 1.78878149e-01, 6.98926864e-01, 6.27106914e-04,
       1.25279078e-01, 1.06782415e-01, 6.27106914e-04, 6.27106914e-04,
       6.27106914e-04, 2.84106892e-02, 2.11661463e-02, 2.97118687e-01,
       6.27106914e-04, 1.51124727e-02, 2.10970464e-04, 7.70852518e-03,
       2.84106892e-02, 5.45352421e-01, 3.42919289e-02, 1.92463331e-01,
       1.13331298e-01, 2.05915377e-02, 1.03427489e-01, 6.27106914e-04,
       1.59672214e-02, 1.23850324e-02, 6.27106914e-04, 1.23850324e-02,
       3.88908981e-02, 7.79726743e-03, 6.27106914e-04, 2.11661463e-02,
       5.60471502e-02, 2.41544803e-02, 2.84106892e-02, 1.63600897e-02,
       2.97118687e-01, 1.78878149e-01, 2.70867100e-03, 1.96200111e-02,
       2.88788204e-02])

In [51]:
y_test_orig = scaler.inverse_transform(y_test.reshape(-1, 1)).ravel()
y_pred_orig = scaler.inverse_transform(y_pred.reshape(-1, 1)).ravel() 

results_df = pd.DataFrame({
    "Actual" : y_test_orig,
    "Predict" : y_pred_orig
})

results_df

     Actual     Predict
0      99.0   89.073424
1      35.0   53.509929
2      34.0   21.331429
3      49.0   43.283643
4      42.0   80.578553
..      ...         ...
160   129.0  211.251387
161   184.0  127.182364
162     0.0    1.925865
163     0.0   13.949828
164     8.0   20.532841

[165 rows x 2 columns]

In [52]:
model.score(x_test, y_test)

0.726078755783095

Random forest classifier

In [53]:
from sklearn.ensemble import RandomForestClassifier 
from sklearn.preprocessing import LabelEncoder 

df = pd.read_csv("penyakit_jantung.csv")

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,female,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,female,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,male,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,female,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,male,0,120,354,0,1,163,1,0.6,2,0,2,1

In [54]:
X = df.drop(columns=["target"])
Y = df[["target"]] 

encoder = LabelEncoder()
X["sex"] = encoder.fit_transform(X["sex"])

kolom = df.drop(columns=["target", "sex"]).columns
print(kolom)

scaler_jantung = MinMaxScaler()
X[['age', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 
   'thalach', 'exang','oldpeak', 'slope', 'ca', 'thal']] = scaler_jantung.fit_transform(X[['age', 'cp', 'trestbps', 'chol', 'fbs', 
                                                                                           'restecg', 'thalach', 'exang','oldpeak', 'slope', 'ca', 'thal']])

X

Index(['age', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang',
       'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,0.708333,0,1.000000,0.481132,0.244292,1.0,0.0,0.603053,0.0,0.370968,0.0,0.00,0.333333
1,0.166667,0,0.666667,0.339623,0.283105,0.0,0.5,0.885496,0.0,0.564516,0.0,0.00,0.666667
2,0.250000,1,0.333333,0.339623,0.178082,0.0,0.0,0.770992,0.0,0.225806,1.0,0.00,0.666667
3,0.562500,0,0.333333,0.245283,0.251142,0.0,0.5,0.816794,0.0,0.129032,1.0,0.00,0.666667
4,0.583333,1,0.000000,0.245283,0.520548,0.0,0.5,0.702290,1.0,0.096774,1.0,0.00,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,0.583333,1,0.000000,0.433962,0.262557,0.0,0.5,0.396947,1.0,0.032258,0.5,0.00,1.000000
299,0.333333,0,1.000000,0.150943,0.315068,0.0,0.5,0.465649,0.0,0.193548,0.5,0.00,1.000000
300,0.812500,0,0.000000,0.471698,0.152968,1.0,0.5,0.534351,0.0,0.548387,0.5,0.50,1.000000
301,0.583333,0,0.000000,0.339623,0.011416,0.0,0.5,0.335878,1.0,0.193548,0.5,0.25,1.000000
302,0.583333,1,0.333333,0.339623,0.251142,0.0,0.0,0.786260,0.0,0.000000,0.5,0.25,0.666667

In [55]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [58]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

model.score(x_test, y_test)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8131868131868132

In [62]:
results = pd.DataFrame({
    "Actual" : y_test["target"].values, 
    "Predict" : y_pred
})

results

    Actual  Predict
0        0        0
1        0        1
2        1        1
3        0        0
4        1        1
..     ...      ...
86       0        0
87       1        1
88       1        1
89       1        1
90       1        1

[91 rows x 2 columns]