In [6]:
import stadata
import pandas as pd

client = stadata.Client("222c257995e148d82784e309c835d7dc")

df = pd.DataFrame(client.list_domain())

df[df["domain_name"] == "Denpasar"]

    domain_id domain_name                      domain_url           level
299      5171    Denpasar  https://denpasarkota.bps.go.id  kota/kabupaten

In [7]:
client.list_statictable(all=True)

,table_id,title,subj_id,subj,updt_date,size,domain
0,2213,Angka Kelahiran Kasar (Crude Birth Rate) Hasil...,12,Kependudukan,2023-07-14 10:06:12,0.07 MB,0000
1,2215,Angka Kelahiran Hasil Long Form SP2020 Menurut...,12,Kependudukan,2023-07-14 10:05:37,0.1 MB,0000
2,2211,Angka Kelahiran Total / Total Fertility Rate (...,12,Kependudukan,2023-07-14 10:05:00,0.07 MB,0000
3,915,Tingkat Inflasi Tahun ke Tahun Gabungan 90 Kot...,3,Inflasi,2023-07-03 12:21:58,0.04 MB,0000
4,914,Tingkat Inflasi Tahun Kalender Gabungan 90 Kot...,3,Inflasi,2023-07-03 12:20:54,0.04 MB,0000
...,...,...,...,...,...,...,...
102250,25,"Luas Wilayah Menurut Distrik di Kota Jayapura,...",153,Geografi,2016-03-23,0.03 MB,9471
102251,23,"Luas Wilayah Menurut Distrik di Kota Jayapura,...",153,Geografi,2016-03-23,0.03 MB,9471
102252,22,Proyeksi jumlah penduduk Provinsi Papua menur...,12,Kependudukan,2016-02-20,0.04 MB,9471
102253,21,Tingkat Inflasi/Deflasi Kota Jayapura,3,Inflasi,2016-02-12,0.03 MB,9471
102254,13,Penduduk Angkatan Kerja Menurut Kabupaten/Kota...,6,Tenaga Kerja,2016-01-29,0.03 MB,9471

In [8]:
client.list_dynamictable(all=True)

,var_id,title,sub_id,sub_name,subcsa_id,subcsa_name,notes,vertical,unit,graph_id,graph_name,domain
0,70,Persentase Penduduk Usia 5 tahun ke atas yang ...,2,Komunikasi,565,Masyarakat Informasi,"&lt;p&gt;Sumber: BPS, Survei Sosial Ekonomi Na...",1.0,Tidak Ada Satuan,1.0,bar,0000
1,111,Persentase Rumah Tangga yang Memiliki/Menguasa...,2,Komunikasi,565,Masyarakat Informasi,"Sumber: BPS, Survei Sosial Ekonomi Nasional (S...",1.0,Tidak Ada Satuan,1.0,bar,0000
2,391,Persentase Rumah Tangga yang Memiliki/Menguasa...,2,Komunikasi,565,Masyarakat Informasi,"Sumber: BPS, Survei Sosial Ekonomi Nasional (S...",1.0,Tidak Ada Satuan,1.0,bar,0000
3,392,Rata-Rata Banyaknya Nomor Telepon Seluler Akti...,2,Komunikasi,565,Masyarakat Informasi,"Sumber: BPS, Survei Sosial Ekonomi Nasional (S...",1.0,Tidak Ada Satuan,1.0,bar,0000
4,393,Persentase Rumah Tangga yang Memiliki/Menguasa...,2,Komunikasi,565,Masyarakat Informasi,"Sumber: BPS, Survei Sosial Ekonomi Nasional (S...",1.0,Tidak Ada Satuan,1.0,bar,0000
...,...,...,...,...,...,...,...,...,...,...,...,...
30608,295,Jumlah korban terdampak bencana menurut kecamatan,152,Lingkungan Hidup,0,NaN,Sumber: Badan Penanggulangan Bencana Daerah Ko...,13.0,Tidak Ada Satuan,1.0,bar,3272
30609,297,Nilai kerugian akibat bencana menurut kecamata...,152,Lingkungan Hidup,0,NaN,Sumber: Badan Penanggulangan Bencana Daerah Ko...,13.0,Rupiah,1.0,bar,3272
30610,299,Berat sampah menurut bulan,152,Lingkungan Hidup,0,NaN,Sumber: Dinas Lingkungan Hidup Kota Sukabumi,18.0,Ton,1.0,bar,3272
30611,99,Luas Daerah,153,Geografi,0,NaN,Luas dalam Kilometer persegi.\nSumber: Bagian ...,13.0,Km2,1.0,bar,3272
30612,162,Jarak ke Ibukota Kota,153,Geografi,0,NaN,Sumber: Bagian Tata Pemerintahan Sekretariat D...,13.0,Kilometer,1.0,bar,3272

In [9]:
client.list_publication(all=True)

,title,issn,sch_date,rl_date,updt_date,size,domain
pub_id,,,,,,,
fafd73df0c782f4c2302fd1a,Buletin Statistik Perdagangan Luar Negeri Impo...,2745-6765,2023-07-28,2023-07-28,NaN,6.74 MB,0000
a52dc1c975c5877cd5903c9c,Statistik Produksi Kehutanan 2022,2580-1740,2023-07-28,2023-07-28,NaN,14.52 MB,0000
8f2ffb811edd9af3673356a7,Statistik Perdagangan Luar Negeri Indonesia Ek...,2745-3960,2023-07-28,2023-07-28,NaN,5.1 MB,0000
87341dcfd8ae9423b2ac7bda,Buletin Statistik Perdagangan Luar Negeri Eksp...,2745-3987,2023-07-28,2023-07-28,NaN,3.53 MB,0000
2296dc4772d2f242e6439bd0,Buletin Statistik Perdagangan Luar Negeri Eksp...,2745-3995,2023-07-28,2023-07-28,NaN,8.35 MB,0000
...,...,...,...,...,...,...,...
79bd30cb5b39389036be11b1,Kecamatan Jayapura Selatan Dalam Angka 2016,-,2017-08-24,2017-08-24,NaN,8 MB,9471
270f3efbe5682f8913346e47,Kecamatan Abepura Dalam Angka 2016,-,2016-07-29,2017-08-24,NaN,11 MB,9471
16d1ab233914236861ae2adc,Statistik Daerah Jayapura Selatan 2016,-,2016-09-26,2017-08-24,NaN,2.87 MB,9471
c4284cd96075097d89276933,Kota Jayapura Dalam Angka 2017,978-602-71354-1-3,2017-08-11,2017-08-11,NaN,9 MB,9471
142d91bd03a972c7e6ab2839,Produk Domestik Regional Bruto Kota Jayapura ...,978-602-71354-2-0,2017-08-10,2017-08-10,NaN,4 MB,9471

In [10]:
client.list_pressrelease(all=True)

,subj_id,subj,title,rl_date,updt_date,size,domain
brs_id,,,,,,,
2035,23,Kemiskinan dan Ketimpangan,"Gini Ratio Maret 2023 tercatat sebesar 0,388.",2023-07-17,NaN,5.2 MB,0000
2016,23,Kemiskinan dan Ketimpangan,Profil Kemiskinan di Indonesia Maret 2023,2023-07-17,2023-07-17,1.24 MB,0000
1967,8,Ekspor-Impor,"Ekspor Juni 2023 mencapai US$20,61 miliar, tur...",2023-07-17,NaN,3.41 MB,0000
2009,20,Harga Perdagangan Besar,"Pada Juni 2023, perubahan Indeks Harga Perdaga...",2023-07-03,NaN,3.75 MB,0000
1991,22,Nilai Tukar Petani,Nilai Tukar Petani (NTP) Juni 2023 sebesar 110...,2023-07-03,NaN,5.31 MB,0000
...,...,...,...,...,...,...,...
16,20,Indeks Harga Perdagangan Besar,Perkembangan Inflasi Provinsi Papua 2017,2018-03-20,NaN,0.43 MB,9471
44,22,Nilai Tukar Petani,Nilai Tukar Petani Provinsi Papua Januari 2018,2018-02-02,NaN,0.64 MB,9471
34,20,Indeks Harga Perdagangan Besar,Perkembangan Indeks Harga Konsumen/Inflasi Kot...,2018-02-02,NaN,0.29 MB,9471
18,17,Transportasi,Perkembangan Transportasi Provinsi Papua Bulan...,2018-02-02,NaN,0.26 MB,9471
7,17,Transportasi,Jumlah Penumpang Angkutan Laut Provinsi Papua ...,2017-10-03,2017-10-03,0.23 MB,9471

In [11]:
import requests
import pandas as pd

# URL data JSON
url = "https://webapi.bps.go.id/v1/api/interoperabilitas/datasource/sensus/id/37/key/222c257995e148d82784e309c835d7dc/"

# Mengambil data dari URL
response = requests.get(url)
data = response.json()

# Normalisasi data JSON ke dalam dataframe Pandas
df = pd.json_normalize(data)

# Tampilkan dataframe
print(df)

  status data-availability                                               data
0     OK         available  [{'page': 1, 'pages': 1, 'per_page': 1, 'count...

In [18]:
for i in df["data"]:
    for z in i:
        if isinstance(z, list):
            for b in z:
                print(b)

{'id': 'sp2020', 'kegiatan': 'Sensus Penduduk 2020', 'tahun_kegiatan': 2020}
{'id': 'sp2010', 'kegiatan': 'Sensus Penduduk 2010', 'tahun_kegiatan': 2010}
{'id': 'st2023', 'kegiatan': 'Sensus Pertanian 2023', 'tahun_kegiatan': 2023}
{'id': 'sp2022', 'kegiatan': 'Long Form Sensus Penduduk 2020', 'tahun_kegiatan': 2022}