In [15]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

In [16]:
np.random.seed(42)

data_size = 50
experience = np.random.randint(1, 21, size=data_size)
education = np.random.randint(1, 5, size=data_size)

noise = np.random.normal(0, 500000, size=data_size)
salary = np.round(1000000 * experience + 500000 * education + noise)

df = pd.DataFrame({
    "Experience" : experience, 
    "Education" : education, 
    "Salary" : salary
})

df.head()

   Experience  Education      Salary
0           7          4   8661539.0
1          20          4  22305838.0
2          15          2  16515500.0
3          11          2  12465640.0
4           8          2   8580391.0

In [17]:
x = df[["Experience", "Education"]]
y = df[["Salary"]]

scaler_x = MinMaxScaler()
x_scaled = scaler_x.fit_transform(x)

scaler_y = MinMaxScaler()
y_norm = scaler_y.fit_transform(y).ravel()

x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_norm, test_size=0.3, random_state=42)

In [18]:
x_test

array([[0.57894737, 1.        ],
       [1.        , 1.        ],
       [0.31578947, 1.        ],
       [0.10526316, 0.        ],
       [0.57894737, 1.        ],
       [0.15789474, 0.66666667],
       [1.        , 0.        ],
       [0.57894737, 1.        ],
       [0.31578947, 0.33333333],
       [0.84210526, 0.66666667],
       [0.05263158, 0.33333333],
       [0.36842105, 0.33333333],
       [0.42105263, 0.        ],
       [0.52631579, 0.33333333],
       [0.52631579, 0.33333333]])

In [19]:
y_test

array([0.61552439, 1.        , 0.37225737, 0.07140196, 0.56623832,
       0.12862297, 0.90452673, 0.57476178, 0.26669953, 0.84163798,
       0.06035633, 0.3151955 , 0.3731285 , 0.47181979, 0.50655404])

In [20]:
model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
y_pred

array([0.57899619, 0.97751686, 0.32992078, 0.05785446, 0.57899619,
       0.15620687, 0.90471087, 0.57899619, 0.28138345, 0.80380295,
       0.03230804, 0.33119854, 0.35674496, 0.48064379, 0.48064379])

In [21]:
model.score(x_test, y_test)

0.992814325133279

In [28]:
new_data = pd.DataFrame({
    "Experience" : [1,10,5],
    "Education" : [1,2,3]
})

new_data_scaled = scaler_x.transform(new_data)

new_predict = model.predict(new_data_scaled)
prediction = scaler_y.inverse_transform(new_predict.reshape(-1, 1))

new_data["Salary"] = np.round(prediction.ravel()).astype(int)
new_data

   Experience  Education    Salary
0           1          1   1332625
1          10          2  10928150
2           5          3   6363786