In [1]:
import pandas as pd 
import seaborn as sns 

data = pd.read_csv("bali_tourist.csv")
data

,year,area,country,January,February,March,April,May,June,July,August,September,October,November,December
0,2019,ASIA PACIFIC,AUSTRALIAN,95536,67474,83002,90265.0,98625,110815,123293,118556,124416,119382,105312,110711
1,2019,ASIA PACIFIC,BHUTAN,60,30,47,38.0,31,31,46,67,43,32,56,60
2,2019,ASIA PACIFIC,BANGLADESH,2262,2094,2489,2264.0,1938,4265,2656,2307,2035,2371,2164,2671
3,2019,ASIA PACIFIC,FIJI,91,73,72,77.0,42,62,2656,80,68,78,89,189
4,2019,ASIA PACIFIC,HONGKONG,1313,1367,764,6.0,1,5,2,1,0,11,0,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,2018,MIDDLE EAST,TURKEY,899,615,750,960.0,712,909,1306,1630,979,707,514,521
358,2018,MIDDLE EAST,UNITED ARAB EMIRATES,170,132,266,264.0,111,293,375,306,164,151,147,201
359,2018,MIDDLE EAST,YAMAN,98,49,76,55.0,23,62,40,52,67,37,60,85
360,2018,MIDDLE EAST,JORDAN,225,153,236,352.0,150,260,389,448,283,255,218,254
361,2018,OTHER NATIONALITIES,OTHER NATIONALITIES,6952,1704,1771,2484.0,2167,3711,2054,1269,1762,2604,3298,673

In [2]:
# no 1 & 2

bulan = data.loc[0:, "January" : "December"].columns
tourist = data.groupby("year")[bulan].sum() 
tourist

,January,February,March,April,May,June,July,August,September,October,November,December
year,,,,,,,,,,,,
2018,358065,452423,492678,516777.0,528512,544550,624366,573766,555903,517889,407213,501211
2019,456218,437537,449637,476327.0,485634,549751,594279,616706,590565,568064,497925,552402

In [3]:
total_tourist = tourist.sum(axis=1)
mean_tourist = tourist.mean(axis=1)
max_2018 = tourist.loc[2018].idxmax()
max_2019 = tourist.loc[2019].idxmax()
min_2018 = tourist.loc[2018].idxmin()
min_2019 = tourist.loc[2019].idxmin()

In [4]:
# no 5

area = data.groupby(["year", "area"])[bulan].sum()
area_max_2018 = area.loc[2018].sum(axis = 1).idxmax()
area_max_2019 = area.loc[2019].sum(axis = 1).idxmax()

print(area_max_2019)
print(area_max_2018)

ASIA PACIFIC
ASIA PACIFIC