In [26]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By 

chrome_driver_path = "/Applications/MAMP/htdocs/local/kodingakademi/Python/python 4/bootcamp batch 3/chromedriver-mac-arm64/chromedriver"

service = Service(chrome_driver_path)
driver = webdriver.Chrome(service=service)

In [13]:
from bs4 import BeautifulSoup

element = driver.find_element(By.CLASS_NAME, "central-textlogo")
soup = BeautifulSoup(element.get_attribute("outerHTML"), "html.parser")
print(soup)

<div class="central-textlogo">
<img alt="" class="central-featured-logo" height="183" src="portal/wikipedia.org/assets/img/Wikipedia-logo-v2.png" srcset="portal/wikipedia.org/assets/img/Wikipedia-logo-v2@1.5x.png 1.5x, portal/wikipedia.org/assets/img/Wikipedia-logo-v2@2x.png 2x" width="200"/>
<h1 class="central-textlogo-wrapper">
<span class="central-textlogo__image sprite svg-Wikipedia_wordmark">
Wikipedia
</span>
<strong class="jsl10n localized-slogan" data-jsl10n="portal.slogan">The Free Encyclopedia</strong>
</h1>
</div>

In [16]:
import pandas as pd

driver.get("https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)")

table = driver.find_element(By.CLASS_NAME, "wikitable")
rows = table.find_elements(By.TAG_NAME, "tr")

data = []
for row in rows:
    cols = row.find_elements(By.TAG_NAME, "td")
    if cols:
        country = cols[0].text
        population = cols[1].text
        data.append([country, population])

df = pd.DataFrame(data, columns=["Country", "Population"])
df.head()

          Country     Population
0           World  8,021,407,192
1           India  1,425,423,212
2        China[a]  1,425,179,569
3   United States    341,534,046
4       Indonesia    278,830,529

In [ ]:
import pandas as pd

driver.get("https://finance.yahoo.com/quote/AAPL/history/?p=AAPL")

table = driver.find_element(By.CLASS_NAME, "table-container")
rows = table.find_elements(By.TAG_NAME, "tr")

data = []
for row in rows:
    cols = row.find_elements(By.TAG_NAME, "td")
    if cols and len(cols) == 7:
        date = cols[0].text
        open = cols[1].text
        high = cols[2].text
        low = cols[3].text
        close = cols[4].text
        adj_close = cols[5].text
        volume = cols[6].text
        data.append([date, open, high, low, close, adj_close, volume])

df = pd.DataFrame(data, columns=["date", "open", "high", "low", "close", "adj_close", "volume"])
df.to_excel("AAPL_stock_data.xlsx", index=False)

           date    open    high     low   close adj_close      volume
0  Apr 15, 2026  258.16  266.56  257.81  266.43    266.43  49,735,000
1  Apr 14, 2026  259.25  261.93  257.19  258.83    258.83  48,370,700
2  Apr 13, 2026  259.73  260.18  256.66  259.20    259.20  36,234,700
3  Apr 10, 2026  259.98  262.19  259.02  260.48    260.48  31,291,500
4   Apr 9, 2026  259.00  261.12  256.07  260.49    260.49  28,121,600

STATISTIK

In [28]:
import numpy as np 
import pandas as pd 
from scipy import stats

In [30]:
data = pd.read_csv("jantung.csv")
thalach = data["thalach"]
thalach

0      150
1      187
2      172
3      178
4      163
      ...
298    123
299    132
300    141
301    115
302    174
Name: thalach, Length: 303, dtype: int64

In [37]:
mean = np.mean(thalach)
median = np.median(thalach)
mode = stats.mode(thalach)
variance = np.var(thalach)
std = np.std(thalach)
skewness = stats.skew(thalach)

print("Mean:", mean)
print("Median:", median)
print(f"nilai = {mode[0]}, jumlah = {mode[1]}")
print("Variance:", variance)
print("Standard Deviation:", std)
print("Skewness:", skewness)

# rata - rata = 180
# batas atas = 180 + 22 = 202
# batas bawah = 180 - 22 = 158

Mean: 149.64686468646866
Median: 153.0
nilai = 162, jumlah = 11
Variance: 522.9148994107329
Standard Deviation: 22.867332581889233
Skewness: -0.5347455419075503