In [21]:
import hvplot.pandas
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("penyakit_jantung.csv")
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,female,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,female,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,male,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,female,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,male,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,male,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,female,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,female,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,female,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,male,1,130,236,0,0,174,0,0.0,1,1,2,0

LINE PLOT

In [11]:
data.hvplot(y = "chol", 
            by = "sex", 
            title='Line Plot', 
            legend='right', 
            kind="line")

# x = jumlah data

:NdOverlay   [sex]
   :Curve   [index]   (chol)

SCATTER PLOT

In [10]:
data.hvplot(y = "chol", 
            by = "sex", 
            title='Scatter plot', 
            legend='right', 
            kind="scatter")

:NdOverlay   [sex]
   :Scatter   [index]   (chol)

PLOT HISTOGRAM

In [12]:
data.hvplot(y = ["trestbps", "chol"], 
            title='Line Plot', 
            legend='right', 
            alpha = 0.5,
            kind="hist")

:NdOverlay   [Variable]
   :Histogram   [chol]   (Count)

BAR PLOT

In [20]:
data.hvplot(y = "chol", 
            x = "sex", 
            title='Bar plot', 
            legend='bottom', 
            kind="bar",
            width=800, height=400)

:Bars   [sex]   (chol)

PLOT AREA

In [8]:
area_plot = data.hvplot.area(x='index', y='C', title='Area Plot', ylabel='Value')
area_plot

DataError: Supplied data does not contain specified dimensions, the following dimensions were not found: ['C']

PandasInterface expects tabular data, for more information on supported datatypes see https://holoviews.org/user_guide/Tabular_Datasets.html

BOX PLOT

In [ ]:
box_plot = data.hvplot.box(y='A', title='Box Plot', ylabel='Value')
box_plot

:BoxWhisker   (A)

HEATMAP PLOT

In [ ]:
heatmap_data = pd.DataFrame(np.random.rand(10, 10), columns=list('ABCDEFGHIJ'))
heatmap = heatmap_data.hvplot.heatmap(title='Heatmap', xlabel='Columns', ylabel='Rows')
heatmap

:HeatMap   [columns,index]   (value)

KOMBINASI PLOT

In [ ]:
# Membuat plot garis untuk kolom 'A' dan 'B'
line_plot_A = data.hvplot.line(y='B', line_color='blue', legend='top_left', title='Combined Line Plot')
line_plot_B = data.hvplot.line(y='C', line_color='red', legend='top_left')

# Menggabungkan kedua plot dalam satu canvas
combined_plot = line_plot_A * line_plot_B
combined_plot

:Overlay
   .Curve.I  :Curve   [index]   (B)
   .Curve.II :Curve   [index]   (C)

GEOSPASIAL

In [ ]:
import bokeh.sampledata

# Unduh data sampel Bokeh terlebih dahulu
bokeh.sampledata.download()

Using data directory: C:\Users\agung\.bokeh\data
Skipping 'CGM.csv' (checksum match)
Skipping 'US_Counties.zip' (checksum match)
Skipping 'us_cities.json' (checksum match)
Skipping 'unemployment09.csv' (checksum match)
Skipping 'AAPL.csv' (checksum match)
Skipping 'FB.csv' (checksum match)
Skipping 'GOOG.csv' (checksum match)
Skipping 'IBM.csv' (checksum match)
Skipping 'MSFT.csv' (checksum match)
Skipping 'WPP2012_SA_DB03_POPULATION_QUINQUENNIAL.zip' (checksum match)
Skipping 'gapminder_fertility.csv' (checksum match)
Skipping 'gapminder_population.csv' (checksum match)
Skipping 'gapminder_life_expectancy.csv' (checksum match)
Skipping 'gapminder_regions.csv' (checksum match)
Skipping 'world_cities.zip' (checksum match)
Skipping 'airports.json' (checksum match)
Skipping 'movies.db.zip' (checksum match)
Skipping 'airports.csv' (checksum match)
Skipping 'routes.csv' (checksum match)
Skipping 'haarcascade_frontalface_default.xml' (checksum match)
Skipping 'SampleSuperstore.csv.zip' (checksum match)
Skipping 'emissions.csv' (checksum match)
Skipping 'titanic_all.csv' (checksum match)

In [ ]:
# Sekarang impor airports setelah mengunduh data
airports = pd.read_csv("airports.csv")
airports

,AirportID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,TZ,Type,source
0,3411,Barter Island LRRS Airport,Barter Island,United States,BTI,PABA,70.134003,-143.582001,2,-9,A,America/Anchorage,airport,OurAirports
1,3413,Cape Lisburne LRRS Airport,Cape Lisburne,United States,LUR,PALU,68.875099,-166.110001,16,-9,A,America/Anchorage,airport,OurAirports
2,3414,Point Lay LRRS Airport,Point Lay,United States,PIZ,PPIZ,69.732903,-163.005005,22,-9,A,America/Anchorage,airport,OurAirports
3,3415,Hilo International Airport,Hilo,United States,ITO,PHTO,19.721399,-155.048004,38,-10,N,Pacific/Honolulu,airport,OurAirports
4,3416,Orlando Executive Airport,Orlando,United States,ORL,KORL,28.545500,-81.332901,113,-5,A,America/New_York,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,11866,Cape Canaveral AFS Skid Strip,Cocoa Beach,United States,XMR,KXMR,28.467600,-80.566597,10,\N,\N,\N,airport,OurAirports
1431,11867,Homey (Area 51) Airport,Groom Lake,United States,\N,KXTA,37.235001,-115.810997,4462,\N,\N,\N,airport,OurAirports
1432,11868,Zanesville Municipal Airport,Zanesville,United States,ZZV,KZZV,39.944401,-81.892097,900,\N,\N,\N,airport,OurAirports
1433,11918,Nenana Municipal Airport,Nenana,United States,ENN,PANN,64.547302,-149.074005,362,\N,\N,\N,airport,OurAirports
1434,11919,Wasilla Airport,Wasilla,United States,WWA,PAWS,61.571701,-149.539993,354,\N,\N,\N,airport,OurAirports

In [ ]:
airports.head(3)

,AirportID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,TZ,Type,source
0,3411,Barter Island LRRS Airport,Barter Island,United States,BTI,PABA,70.134003,-143.582001,2,-9,A,America/Anchorage,airport,OurAirports
1,3413,Cape Lisburne LRRS Airport,Cape Lisburne,United States,LUR,PALU,68.875099,-166.110001,16,-9,A,America/Anchorage,airport,OurAirports
2,3414,Point Lay LRRS Airport,Point Lay,United States,PIZ,PPIZ,69.732903,-163.005005,22,-9,A,America/Anchorage,airport,OurAirports

In [ ]:
airports.dtypes

AirportID      int64
Name          object
City          object
Country       object
IATA          object
ICAO          object
Latitude     float64
Longitude    float64
Altitude       int64
Timezone      object
DST           object
TZ            object
Type          object
source        object
dtype: object

In [ ]:
airports.hvplot.points(
    'Longitude', 'Latitude', geo=True, tiles=True, color='red', alpha=0.2
)

:Overlay
   .WMTS.I   :WMTS   [Longitude,Latitude]
   .Points.I :Points   [Longitude,Latitude]