In [1]:
import pandas as pd 
import numpy as np

data = pd.read_csv("data/penyakit_jantung.csv")
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,female,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,female,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,male,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,female,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,male,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,male,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,female,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,female,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,female,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,male,1,130,236,0,0,174,0,0.0,1,1,2,0

MEAN

In [2]:
np.mean(data["trestbps"])

131.62376237623764

MEDIAN

In [3]:
np.median(data["trestbps"])

130.0

MODE

In [4]:
from scipy import stats as st

mode = st.mode(data["trestbps"])
print(mode)
print(mode[0])
print(mode[1])

ModeResult(mode=120, count=37)
120
37

VARIANS

In [5]:
varian = np.var(data["trestbps"])
varian

306.5713165375944

STANDAR DEVIASI

In [6]:
std = np.std(data["trestbps"])
std

17.509178065734393

SKEWNESS

In [7]:
skew = st.skew(data["trestbps"])
skew

0.7102300604861443

KUARTIL

In [8]:
# Menghitung kuartil
q1 = np.percentile(data["trestbps"], 25) 
q2 = np.percentile(data["trestbps"], 50)  
q3 = np.percentile(data["trestbps"], 75)  

# Menghitung IQR (rentang interkuartil)
iqr = q3 - q1

# Mencari data outlier
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

In [9]:
outliers = []

for x in data["trestbps"]:
  if x < lower_bound or x > upper_bound:
    outliers.append(x)

print("Q1:", q1)
print("Q2 (Median):", q2)
print("Q3:", q3)
print("IQR:", iqr)
print("batas bawah:", lower_bound)
print("batas atas:", upper_bound)
print("outliers:",outliers)

Q1: 120.0
Q2 (Median): 130.0
Q3: 140.0
IQR: 20.0
batas bawah: 90.0
batas atas: 170.0
outliers: [172, 178, 180, 180, 200, 174, 192, 178, 180]

ASSIGNMENT

In [ ]:
# NO 1

data = pd.read_csv("data/lalulintas.csv")
data

,bulan,wilayah,bap_tilang,stop_operasi,bap_polisi,stop_operasi_polisi,penderekan,ocp_roda_dua,ocp_roda_empat,angkut_motor
0,Januari,Bidang Dalops,44,139,0,0,73,0,0,0
1,Januari,Sudinhub Jakarta Pusat,47,2,52,0,184,237,15,97
2,Januari,Sudinhub Jakarta Utara,166,27,0,0,174,0,0,0
3,Januari,Sudinhub Jakarta Selatan,44,1,0,0,61,42,75,0
4,Januari,Sudinhub Jakarta Barat,184,70,0,0,202,10,5,0
5,Januari,Sudinhub Jakarta Timur,191,141,0,0,137,0,0,0
6,Februari,Bidang Dalops,37,143,0,0,95,2,1,0
7,Februari,Sudinhub Jakarta Pusat,48,7,42,0,175,396,21,143
8,Februari,Sudinhub Jakarta Utara,251,27,31,0,255,3,0,0
9,Februari,Sudinhub Jakarta Selatan,129,12,0,0,155,446,110,0
10,Februari,Sudinhub Jakarta Barat,229,60,0,0,245,12,4,0
11,Februari,Sudinhub Jakarta Timur,276,146,0,0,299,0,0,0
12,Maret,Bidang Dalops,90,203,0,0,150,18,2,0
13,Maret,Sudinhub Jakarta Pusat,68,10,0,0,146,216,1,58
14,Maret,Sudinhub Jakarta Utara,323,37,0,0,285,0,0,0
15,Maret,Sudinhub Jakarta Selatan,479,51,0,0,325,221,87,0
16,Maret,Sudinhub Jakarta Barat,270,101,0,0,318,20,11,0
17,Maret,Sudinhub Jakarta Timur,253,129,0,0,291,22,0,0
18,April,Bidang Dalops,78,108,0,0,139,0,2,0
19,April,Sudinhub Jakarta Pusat,93,21,0,0,166,99,5,117
20,April,Sudinhub Jakarta Utara,293,22,12,0,165,0,0,0
21,April,Sudinhub Jakarta Selatan,454,42,0,0,261,423,64,0
22,April,Sudinhub Jakarta Barat,233,97,0,0,252,0,1,0
23,April,Sudinhub Jakarta Timur,274,113,0,0,264,0,0,0
24,Mei,Bidang Dalops,47,88,0,0,57,0,0,0
25,Mei,Sudinhub Jakarta Pusat,30,10,0,0,46,447,72,244
26,Mei,Sudinhub Jakarta Utara,174,10,16,0,149,0,0,0
27,Mei,Sudinhub Jakarta Selatan,203,29,2,0,169,272,28,0
28,Mei,Sudinhub Jakarta Barat,156,82,0,0,107,0,0,0
29,Mei,Sudinhub Jakarta Timur,162,107,0,0,157,0,0,0
30,Juni,Bidang Dalops,113,129,0,0,119,7,2,0
31,Juni,Sudinhub Jakarta Pusat,24,9,0,0,90,806,8,414
32,Juni,Sudinhub Jakarta Utara,365,29,39,0,206,0,0,0
33,Juni,Sudinhub Jakarta Selatan,390,22,16,0,188,277,51,0
34,Juni,Sudinhub Jakarta Barat,176,81,0,0,157,62,6,0
35,Juni,Sudinhub Jakarta Timur,217,116,0,0,203,0,0,0
36,Juli,Bidang Dalops,72,80,0,0,38,0,0,0
37,Juli,Sudinhub Jakarta Pusat,12,6,0,0,11,146,3,0
38,Juli,Sudinhub Jakarta Utara,224,20,24,0,54,0,0,19
39,Juli,Sudinhub Jakarta Selatan,95,2,8,0,25,160,6,0
40,Juli,Sudinhub Jakarta Barat,36,32,0,0,29,0,0,0
41,Juli,Sudinhub Jakarta Timur,104,72,0,0,110,0,0,0

In [ ]:
# NO 2

numerik = data.iloc[0:, 2:]
numerik

,bap_tilang,stop_operasi,bap_polisi,stop_operasi_polisi,penderekan,ocp_roda_dua,ocp_roda_empat,angkut_motor
0,44,139,0,0,73,0,0,0
1,47,2,52,0,184,237,15,97
2,166,27,0,0,174,0,0,0
3,44,1,0,0,61,42,75,0
4,184,70,0,0,202,10,5,0
5,191,141,0,0,137,0,0,0
6,37,143,0,0,95,2,1,0
7,48,7,42,0,175,396,21,143
8,251,27,31,0,255,3,0,0
9,129,12,0,0,155,446,110,0
10,229,60,0,0,245,12,4,0
11,276,146,0,0,299,0,0,0
12,90,203,0,0,150,18,2,0
13,68,10,0,0,146,216,1,58
14,323,37,0,0,285,0,0,0
15,479,51,0,0,325,221,87,0
16,270,101,0,0,318,20,11,0
17,253,129,0,0,291,22,0,0
18,78,108,0,0,139,0,2,0
19,93,21,0,0,166,99,5,117
20,293,22,12,0,165,0,0,0
21,454,42,0,0,261,423,64,0
22,233,97,0,0,252,0,1,0
23,274,113,0,0,264,0,0,0
24,47,88,0,0,57,0,0,0
25,30,10,0,0,46,447,72,244
26,174,10,16,0,149,0,0,0
27,203,29,2,0,169,272,28,0
28,156,82,0,0,107,0,0,0
29,162,107,0,0,157,0,0,0
30,113,129,0,0,119,7,2,0
31,24,9,0,0,90,806,8,414
32,365,29,39,0,206,0,0,0
33,390,22,16,0,188,277,51,0
34,176,81,0,0,157,62,6,0
35,217,116,0,0,203,0,0,0
36,72,80,0,0,38,0,0,0
37,12,6,0,0,11,146,3,0
38,224,20,24,0,54,0,0,19
39,95,2,8,0,25,160,6,0
40,36,32,0,0,29,0,0,0
41,104,72,0,0,110,0,0,0

In [ ]:
kategori = data.iloc[0:, 0:2]
kategori

       bulan                   wilayah
0    Januari             Bidang Dalops
1    Januari    Sudinhub Jakarta Pusat
2    Januari    Sudinhub Jakarta Utara
3    Januari  Sudinhub Jakarta Selatan
4    Januari    Sudinhub Jakarta Barat
5    Januari    Sudinhub Jakarta Timur
6   Februari             Bidang Dalops
7   Februari    Sudinhub Jakarta Pusat
8   Februari    Sudinhub Jakarta Utara
9   Februari  Sudinhub Jakarta Selatan
10  Februari    Sudinhub Jakarta Barat
11  Februari    Sudinhub Jakarta Timur
12     Maret             Bidang Dalops
13     Maret    Sudinhub Jakarta Pusat
14     Maret    Sudinhub Jakarta Utara
15     Maret  Sudinhub Jakarta Selatan
16     Maret    Sudinhub Jakarta Barat
17     Maret    Sudinhub Jakarta Timur
18     April             Bidang Dalops
19     April    Sudinhub Jakarta Pusat
20     April    Sudinhub Jakarta Utara
21     April  Sudinhub Jakarta Selatan
22     April    Sudinhub Jakarta Barat
23     April    Sudinhub Jakarta Timur
24       Mei             Bidang Dalops
25       Mei    Sudinhub Jakarta Pusat
26       Mei    Sudinhub Jakarta Utara
27       Mei  Sudinhub Jakarta Selatan
28       Mei    Sudinhub Jakarta Barat
29       Mei    Sudinhub Jakarta Timur
30      Juni             Bidang Dalops
31      Juni    Sudinhub Jakarta Pusat
32      Juni    Sudinhub Jakarta Utara
33      Juni  Sudinhub Jakarta Selatan
34      Juni    Sudinhub Jakarta Barat
35      Juni    Sudinhub Jakarta Timur
36      Juli             Bidang Dalops
37      Juli    Sudinhub Jakarta Pusat
38      Juli    Sudinhub Jakarta Utara
39      Juli  Sudinhub Jakarta Selatan
40      Juli    Sudinhub Jakarta Barat
41      Juli    Sudinhub Jakarta Timur

In [ ]:
# NO 3

kolom_numerik = numerik.columns
kolom_numerik

Index(['bap_tilang', 'stop_operasi', 'bap_polisi', 'stop_operasi_polisi',
       'penderekan', 'ocp_roda_dua', 'ocp_roda_empat', 'angkut_motor'],
      dtype='object')

In [ ]:
for i in kolom_numerik:
    mean = np.mean(data[i])
    median = np.median(data[i])
    print(f"{i} = mean({mean}), median({median})")

bap_tilang = mean(170.33333333333334), median(164.0)
stop_operasi = mean(62.69047619047619), median(46.5)
bap_polisi = mean(5.761904761904762), median(0.0)
stop_operasi_polisi = mean(0.0), median(0.0)
penderekan = mean(160.28571428571428), median(157.0)
ocp_roda_dua = mean(103.42857142857143), median(5.0)
ocp_roda_empat = mean(13.80952380952381), median(1.0)
angkut_motor = mean(26.0), median(0.0)

In [ ]:
# NO 4

kolom_numerik = numerik.columns
kolom_numerik

Index(['bap_tilang', 'stop_operasi', 'bap_polisi', 'stop_operasi_polisi',
       'penderekan', 'ocp_roda_dua', 'ocp_roda_empat', 'angkut_motor'],
      dtype='object')

In [ ]:
for i in kolom_numerik:
    std = np.std(data[i])
    q1 = np.percentile(data[i], 25)
    q2 = np.percentile(data[i], 50)
    q3 = np.percentile(data[i], 75)
    print(f"{i} = q1({q1}), q2({q2}), q3({q3}), std({std})")

bap_tilang = q1(69.0), q2(164.0), q3(246.5), std(119.05954226005828)
stop_operasi = q1(20.25), q2(46.5), q3(105.5), std(51.81950731016728)
bap_polisi = q1(0.0), q2(0.0), q3(0.0), std(12.776111495416384)
stop_operasi_polisi = q1(0.0), q2(0.0), q3(0.0), std(0.0)
penderekan = q1(98.0), q2(157.0), q3(205.25), std(84.50170066315818)
ocp_roda_dua = q1(0.0), q2(5.0), q3(156.5), std(176.0025896531805)
ocp_roda_empat = q1(0.0), q2(1.0), q3(7.5), std(27.1514606247796)
angkut_motor = q1(0.0), q2(0.0), q3(0.0), std(77.12266049550392)

In [ ]:
# NO 5

bulan = data["bulan"].unique()
bulan

array(['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli'],
      dtype=object)

In [ ]:
for i in bulan:
    cek = data.loc[data["bulan"] == i]
    rata = np.mean(cek["bap_tilang"])
    print(f"{i} = {rata}")

Januari = 112.66666666666667
Februari = 161.66666666666666
Maret = 247.16666666666666
April = 237.5
Mei = 128.66666666666666
Juni = 214.16666666666666
Juli = 90.5